In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [73]:
import tensorflow as tf
import numpy as np

In [3]:
tf.VERSION

'1.13.1'

In [5]:
dir(tf)

['AUTO_REUSE',
 'AggregationMethod',
 'Assert',
 'AttrValue',
 'COMPILER_VERSION',
 'CXX11_ABI_FLAG',
 'ConditionalAccumulator',
 'ConditionalAccumulatorBase',
 'ConfigProto',
 'DType',
 'DeviceSpec',
 'Dimension',
 'Event',
 'FIFOQueue',
 'FixedLenFeature',
 'FixedLenSequenceFeature',
 'FixedLengthRecordReader',
 'GIT_VERSION',
 'GPUOptions',
 'GRAPH_DEF_VERSION',
 'GRAPH_DEF_VERSION_MIN_CONSUMER',
 'GRAPH_DEF_VERSION_MIN_PRODUCER',
 'GradientTape',
 'Graph',
 'GraphDef',
 'GraphKeys',
 'GraphOptions',
 'HistogramProto',
 'IdentityReader',
 'IndexedSlices',
 'InteractiveSession',
 'LMDBReader',
 'LogMessage',
 'MONOLITHIC_BUILD',
 'MetaGraphDef',
 'NameAttrList',
 'NoGradient',
 'NodeDef',
 'NotDifferentiable',
 'OpError',
 'Operation',
 'OptimizerOptions',
 'PaddingFIFOQueue',
 'Print',
 'PriorityQueue',
 'QUANTIZED_DTYPES',
 'QueueBase',
 'RaggedTensor',
 'RandomShuffleQueue',
 'ReaderBase',
 'RegisterGradient',
 'RunMetadata',
 'RunOptions',
 'Session',
 'SessionLog',
 'SparseCondi

In [19]:
x1 = tf.constant(4)
x2 = tf.constant(5)
z = tf.add(x1, x2)
sess = tf.Session()
print(sess.run(z))
sess.close()

9


In [43]:
x = tf.placeholder(tf.float32, [2,3])
y = tf.placeholder(tf.float32, [3,2])
output = tf.matmul(x, y)
output2 = tf.matmul(output, x)
with tf.Session() as sess:
    result = sess.run(output2, feed_dict={x: [[2,4,5],[5,3,2]], y: [[3,6],[1,3],[2,3]]})

In [44]:
result

array([[235., 197., 178.],
       [269., 223., 200.]], dtype=float32)

In [59]:
x = tf.placeholder(tf.float32, [2,3])
y = tf.placeholder(tf.float32, [3,2])
output = tf.matmul(x, y)
sess = tf.Session()
print(sess.run(output, feed_dict={x: [[2,4,5],[5,3,2]], y: [[3,6],[1,3],[2,3]]}))

[[20. 39.]
 [22. 45.]]


In [60]:
output2 = tf.matmul(output, x)
print(sess.run(output2, feed_dict={x: [[2,4,5],[5,3,2]], y: [[3,6],[1,3],[2,3]]}))

[[235. 197. 178.]
 [269. 223. 200.]]


In [67]:
z = tf.Variable([4,5,2], dtype = 'float32' )


In [68]:
zz =z + output2

In [71]:
print(zz)

Tensor("add_18:0", shape=(2, 3), dtype=float32)


In [51]:
sess.close()

In [57]:
tf.Variable?

Линейная регрессия на TensorFlow

In [76]:
n_samples, batch_size, num_steps = 1000, 100, 20000
X_data = np.random.uniform(1, 10, (n_samples, 1))
y_data = 2 * X_data + 1 + np.random.normal(0, 2, (n_samples, 1))
X = tf.placeholder(tf.float32, shape=(batch_size, 1))
y = tf.placeholder(tf.float32, shape=(batch_size, 1))
with tf.variable_scope('linear-regression'):
    k = tf.Variable(tf.random_normal((1, 1)), name='slope')
    b = tf.Variable(tf.zeros((1,)), name='bias')
y_pred = tf.matmul(X, k) + b
loss = tf.reduce_sum((y - y_pred) ** 2)
learning_rate = tf.placeholder(tf.float32)
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)
display_step = 100
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for i in range(num_steps):
        indices = np.random.choice(n_samples, batch_size)
        X_batch, y_batch = X_data[indices], y_data[indices]
        _, loss_val, k_val, b_val = sess.run([ optimizer, loss, k, b ], feed_dict = { X : X_batch, y : y_batch , learning_rate: 0.1})
        if (i+1) % display_step == 0:
            print('Эпоха %d: %.8f, k=%.4f, b=%.4f' % (i+1, loss_val, k_val, b_val))

Эпоха 100: nan, k=nan, b=nan
Эпоха 200: nan, k=nan, b=nan
Эпоха 300: nan, k=nan, b=nan
Эпоха 400: nan, k=nan, b=nan
Эпоха 500: nan, k=nan, b=nan
Эпоха 600: nan, k=nan, b=nan
Эпоха 700: nan, k=nan, b=nan
Эпоха 800: nan, k=nan, b=nan
Эпоха 900: nan, k=nan, b=nan
Эпоха 1000: nan, k=nan, b=nan
Эпоха 1100: nan, k=nan, b=nan
Эпоха 1200: nan, k=nan, b=nan
Эпоха 1300: nan, k=nan, b=nan
Эпоха 1400: nan, k=nan, b=nan
Эпоха 1500: nan, k=nan, b=nan
Эпоха 1600: nan, k=nan, b=nan
Эпоха 1700: nan, k=nan, b=nan
Эпоха 1800: nan, k=nan, b=nan
Эпоха 1900: nan, k=nan, b=nan
Эпоха 2000: nan, k=nan, b=nan
Эпоха 2100: nan, k=nan, b=nan
Эпоха 2200: nan, k=nan, b=nan
Эпоха 2300: nan, k=nan, b=nan
Эпоха 2400: nan, k=nan, b=nan
Эпоха 2500: nan, k=nan, b=nan
Эпоха 2600: nan, k=nan, b=nan
Эпоха 2700: nan, k=nan, b=nan
Эпоха 2800: nan, k=nan, b=nan
Эпоха 2900: nan, k=nan, b=nan
Эпоха 3000: nan, k=nan, b=nan
Эпоха 3100: nan, k=nan, b=nan
Эпоха 3200: nan, k=nan, b=nan
Эпоха 3300: nan, k=nan, b=nan
Эпоха 3400: nan, k=